version: '2.2'

services:
  postgres:
    image: postgres:10-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aula
      - POSTGRES_DB=nutri
